package SeleniumPack;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class TestJUnit {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 System.setProperty("webdriver.chrome.driver","./drivers/chromedriver.exe");
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void test1() {
 driver.get("https://www.calculator.net/calorie-calculator.html");
 driver.manage().window().setSize(new Dimension(786, 816));
 driver.findElement(By.id("cage")).clear();
 driver.findElement(By.id("cage")).click();
 driver.findElement(By.id("cage")).sendKeys("45");
 driver.findElement(By.cssSelector("td > .cbcontainer:nth-child(2) > .rbmark")).click();
 driver.findElement(By.id("cheightmeter")).click();
 driver.findElement(By.id("cheightmeter")).sendKeys("200");
 driver.findElement(By.id("ckg")).click();
 driver.findElement(By.id("ckg")).sendKeys("17");
 driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(2)")).click();
}
}
